[package]
name = "forge-ir"
version = "0.1.0"
edition = "2024"
description = "Forge IR: SSA-form intermediate representation types, builder, parser, and analysis"

[dependencies]
smallvec = "1"
thiserror = "2"
dashu = "0.5.0"
bitflags = "2"
logos = "0.16.1"
lalrpop-util = "0.23"

[build-dependencies]
lalrpop = "0.23.1"
