//! 构建脚本：跟踪 `isa/*.toml` 变更。
//!
//! 背景：`isa_from_file!` 是 proc-macro，运行时用 `std::fs::read_to_string`
//! 读取 TOML——cargo 无法感知 proc-macro 内部读取的文件，修改 TOML 不会
//! 触发 forge-codegen 重编（历史上需手动 `cargo clean -p forge-codegen`）。
//!
//! 方案：`cargo:rerun-if-changed` 声明 TOML 依赖 + 把 TOML 的修改时间写入
//! OUT_DIR 下的 probe 文件，forge-codegen 的 lib.rs `include!` 该 probe——
//! TOML 变化 → probe 变化 → lib 重编 → 宏重新读取 TOML。

use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    // workspace 根：crates/backend/forge-codegen → 上三级
    let isa_dir = manifest.join("../../..").join("isa");
    let tomls: Vec<PathBuf> = std::fs::read_dir(&isa_dir)
        .map(|rd| {
            rd.filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|x| x == "toml"))
                .collect()
        })
        .unwrap_or_default();

    let mut stamp = String::from("// isa/*.toml probe (auto-generated by build.rs)\n");
    for t in &tomls {
        println!("cargo:rerun-if-changed={}", t.display());
        let m = std::fs::metadata(t)
            .and_then(|m| m.modified())
            .map(|t| format!("{:?}", t))
            .unwrap_or_default();
        stamp.push_str(&format!(
            "// {}: {}\n",
            t.file_name().unwrap_or_default().to_string_lossy(),
            m
        ));
    }

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out.join("isa_probe.rs"), stamp).expect("write isa_probe.rs");
}
