//! Forge Assembler — runtime data types for DSL-generated assembler code.
//!
//! Zero-dependency crate providing the shared types consumed by assembler code
//! generated by the `forge-dsl` proc macro at compile time.

/// Field type — determines how an operand value is interpreted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FieldType {
    // ── signed integer immediates ──
    I8,
    I16,
    I32,
    I64,
    // ── unsigned integer immediates ──
    U8,
    U16,
    U32,
    U64,
    // ── float immediates ──
    F32,
    F64,
    // ── virtual registers ──
    Ireg,
    Freg,
    // ── physical registers ──
    GprReg,
    XmmReg,
    // ── structured ──
    MemRef,
    // ── special ──
    BlockTarget,
    CondCode,
    Opsize,
}

/// A single entry in the assembler mnemonic lookup table.
#[derive(Debug, Clone)]
pub struct AsmEntry {
    pub mnemonic: String,
    pub inst_name: String,
    pub template_fields: Vec<(String, FieldType)>,
}

/// Runtime assembler lookup table — generated at compile time by the DSL,
/// consumed at runtime by `parse_insts`.
#[derive(Debug, Clone)]
pub struct AsmLookupTable {
    pub entries: Vec<AsmEntry>,
    pub cc_entries: Vec<(String, String, u8)>,
    pub inst_names: Vec<String>,
}

/// Runtime operand value — intermediate representation after parsing ASM text.
#[derive(Debug, Clone)]
pub enum OperandValue {
    Reg { index: u8 },
    VReg(u32),
    Imm(i64),
    Float(f64),
    Label(String),
    Ident(String),
}

impl AsmLookupTable {
    pub fn find(&self, mnemonic: &str) -> Vec<&AsmEntry> {
        self.entries
            .iter()
            .filter(|e| e.mnemonic == mnemonic)
            .collect()
    }

    pub fn find_cc(&self, mnemonic: &str) -> Option<(String, u8)> {
        self.cc_entries
            .iter()
            .find(|(m, ..)| m == mnemonic)
            .map(|(_, inst_name, val)| (inst_name.clone(), *val))
    }
}

// ============================================================
// 测试
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_lookup() -> AsmLookupTable {
        AsmLookupTable {
            entries: vec![
                AsmEntry {
                    mnemonic: "add".to_string(),
                    inst_name: "ADD".to_string(),
                    template_fields: vec![
                        ("rd".to_string(), FieldType::Ireg),
                        ("rs1".to_string(), FieldType::Ireg),
                        ("rs2".to_string(), FieldType::Ireg),
                    ],
                },
                AsmEntry {
                    mnemonic: "add".to_string(),
                    inst_name: "ADDI".to_string(),
                    template_fields: vec![
                        ("rd".to_string(), FieldType::Ireg),
                        ("rs1".to_string(), FieldType::Ireg),
                        ("imm".to_string(), FieldType::I16),
                    ],
                },
                AsmEntry {
                    mnemonic: "sub".to_string(),
                    inst_name: "SUB".to_string(),
                    template_fields: vec![
                        ("rd".to_string(), FieldType::Ireg),
                        ("rs1".to_string(), FieldType::Ireg),
                        ("rs2".to_string(), FieldType::Ireg),
                    ],
                },
            ],
            cc_entries: vec![
                ("eq".to_string(), "BEQ".to_string(), 0),
                ("ne".to_string(), "BNE".to_string(), 1),
            ],
            inst_names: vec!["ADD".to_string(), "ADDI".to_string(), "SUB".to_string()],
        }
    }

    #[test]
    fn asm_lookup_find_exact_match() {
        let tbl = sample_lookup();
        let results = tbl.find("add");
        assert_eq!(results.len(), 2);
    }

    #[test]
    fn asm_lookup_find_single_match() {
        let tbl = sample_lookup();
        let results = tbl.find("sub");
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].inst_name, "SUB");
    }

    #[test]
    fn asm_lookup_find_no_match() {
        let tbl = sample_lookup();
        let results = tbl.find("nonexistent");
        assert!(results.is_empty());
    }

    #[test]
    fn asm_lookup_find_cc_found() {
        let tbl = sample_lookup();
        let result = tbl.find_cc("eq");
        assert!(result.is_some());
        let (inst_name, val) = result.unwrap();
        assert_eq!(inst_name, "BEQ");
        assert_eq!(val, 0);
    }

    #[test]
    fn asm_lookup_find_cc_not_found() {
        let tbl = sample_lookup();
        let result = tbl.find_cc("gt");
        assert!(result.is_none());
    }

    #[test]
    fn field_type_clone_and_eq() {
        let ft = FieldType::I32;
        assert_eq!(ft, FieldType::I32);
        assert_ne!(ft, FieldType::I64);
    }

    #[test]
    fn operand_value_reg() {
        let r = OperandValue::Reg { index: 5 };
        assert!(matches!(r, OperandValue::Reg { index: 5 }));
    }

    #[test]
    fn operand_value_imm() {
        let i = OperandValue::Imm(-42);
        assert!(matches!(i, OperandValue::Imm(-42)));
    }

    #[test]
    fn operand_value_label() {
        let l = OperandValue::Label("loop".to_string());
        assert!(matches!(l, OperandValue::Label(ref s) if s == "loop"));
    }

    #[test]
    fn asm_entry_fields() {
        let entry = AsmEntry {
            mnemonic: "mv".to_string(),
            inst_name: "ADDI".to_string(),
            template_fields: vec![
                ("rd".to_string(), FieldType::Ireg),
                ("rs1".to_string(), FieldType::Ireg),
            ],
        };
        assert_eq!(entry.mnemonic, "mv");
        assert_eq!(entry.inst_name, "ADDI");
        assert_eq!(entry.template_fields.len(), 2);
    }

    #[test]
    fn asm_entry_debug_clone() {
        let entry = AsmEntry {
            mnemonic: "nop".to_string(),
            inst_name: "ADDI".to_string(),
            template_fields: vec![],
        };
        let cloned = entry.clone();
        assert_eq!(cloned.mnemonic, entry.mnemonic);
        assert!(format!("{:?}", entry).contains("nop"));
    }
}
