//! Encoding primitives — ISA-agnostic bit packing.
//!
//! - **pack_bits** / **pack_bits_label** — universal bit-field packing (packer.rs)
//! - **pack!** / **pack_label!** — declarative macros for DSL-generated code (macros.rs)
//!
//! All ISA-specific encoding helpers (modrm, sib, REX, VEX, etc.) are
//! now generated by the DSL and live in the ISA module output.

pub mod macros;
pub mod packer;

pub use packer::*;

// Tests are in packer.rs and macros.rs
