//! Composite brick specification.
//!
//! ⚠️ **Experimental — not yet implemented.** This layer (structural bricks
//! wired from atoms) has no instantiation engine yet; only the data model is
//! present. Prefer composing via [`IrGraph`](crate::IrGraph) builder methods
//! and the `build_xxx` op constructors generated by `define_lowering!`.
//!
//! A [`CompositeSpec`] describes a composite structure built from atoms and
//! other composites. It defines:
//! - Input/output ports (same as atoms)
//! - Internal connection graph (which bricks are connected to which)
//!
//! When instantiated, the graph is expanded into concrete IR nodes.

use crate::atom::{OpTag, PortSpec, RegionSpec};
use crate::attr::{AttrValue, Symbol};
// GraphValue and NodeId used in expanded code
use std::collections::HashMap;

// ============================================================
// CompositeNode
// ============================================================

/// A node in the composite graph — represents an instance of an atom
/// or another composite.
#[derive(Clone, Debug)]
pub struct CompositeNode {
    /// The operation tag of the brick being instantiated.
    pub op: OpTag,
    /// A label for this node (for referencing in edges).
    pub label: Option<String>,
    /// Static attributes for this node instance.
    pub attrs: HashMap<Symbol, AttrValue>,
}

// ============================================================
// CompositeEdge
// ============================================================

/// An edge in the composite graph — connects a source port to a
/// destination port.
#[derive(Clone, Debug)]
pub enum CompositeEdge {
    /// Value flow: source_node.output_port → dest_node.input_port
    ValueFlow {
        src_node: String,
        src_port: String,
        dst_node: String,
        dst_port: String,
    },
    /// Block target: a block label → dest_node's region port
    BlockTarget {
        src_block: String,
        dst_node: String,
        dst_region: String,
    },
    /// External input → node's input port
    ExternalInput {
        src_port: String,
        dst_node: String,
        dst_port: String,
    },
    /// Node's output port → external output
    ExternalOutput {
        src_node: String,
        src_port: String,
        dst_port: String,
    },
}

// ============================================================
// CompositeBlock
// ============================================================

/// A block declaration inside a composite graph.
#[derive(Clone, Debug)]
pub struct CompositeBlock {
    /// Block label (for referencing in edges).
    pub label: String,
    /// Block parameters.
    pub params: Vec<(String, forge_ir::TypeId)>,
    /// Whether this block is implicit (created by the framework).
    pub implicit: bool,
    /// Is this the merge/exit block?
    pub is_merge: bool,
}

// ============================================================
// CompositeSpec
// ============================================================

/// Specification for a composite brick.
///
/// A composite defines:
/// - Its external interface (inputs, outputs, regions)
/// - Its internal structure (nodes + edges + blocks = connection graph)
///
/// When the `define_lowering!` macro encounters a `struct { ... }` definition,
/// it parses the `graph { ... }` block into a `CompositeSpec`. The macro then
/// generates a Rust function that instantiates the composite by creating the
/// corresponding nodes/edges/blocks in an [`IrGraph`](crate::IrGraph).
#[derive(Clone, Debug)]
pub struct CompositeSpec {
    /// Composite name.
    pub name: String,
    /// Input value ports.
    pub inputs: Vec<PortSpec>,
    /// Output value ports.
    pub outputs: Vec<PortSpec>,
    /// Region ports.
    pub regions: Vec<RegionSpec>,
    /// Internal nodes (atoms and sub-composites).
    pub nodes: Vec<CompositeNode>,
    /// Edges connecting nodes together.
    pub edges: Vec<CompositeEdge>,
    /// Blocks declared in the graph.
    pub blocks: Vec<CompositeBlock>,
    /// Whether this composite has an implicit merge block.
    pub has_implicit_merge: bool,
}

impl CompositeSpec {
    /// Create a new empty composite specification.
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            inputs: Vec::new(),
            outputs: Vec::new(),
            regions: Vec::new(),
            nodes: Vec::new(),
            edges: Vec::new(),
            blocks: Vec::new(),
            has_implicit_merge: false,
        }
    }

    /// Add an input value port.
    pub fn add_input(&mut self, name: &str, ty: forge_ir::TypeId) {
        self.inputs.push(PortSpec::value_in(name, ty));
    }

    /// Add an output value port.
    pub fn add_output(&mut self, name: &str, ty: forge_ir::TypeId) {
        self.outputs.push(PortSpec::value_out(name, ty));
    }

    /// Add a region port.
    pub fn add_region(&mut self, name: &str, optional: bool) {
        self.regions.push(if optional {
            RegionSpec::optional(name)
        } else {
            RegionSpec::required(name)
        });
    }

    /// Add an internal node (atom or sub-composite instance).
    pub fn add_node(&mut self, op: OpTag, label: &str) {
        self.nodes.push(CompositeNode {
            op,
            label: Some(label.to_string()),
            attrs: HashMap::new(),
        });
    }

    /// Add an unnamed internal node.
    pub fn add_anonymous_node(&mut self, op: OpTag) {
        self.nodes.push(CompositeNode {
            op,
            label: None,
            attrs: HashMap::new(),
        });
    }

    /// Add a value flow edge.
    pub fn add_value_edge(
        &mut self,
        src_node: &str,
        src_port: &str,
        dst_node: &str,
        dst_port: &str,
    ) {
        self.edges.push(CompositeEdge::ValueFlow {
            src_node: src_node.to_string(),
            src_port: src_port.to_string(),
            dst_node: dst_node.to_string(),
            dst_port: dst_port.to_string(),
        });
    }

    /// Add an external input edge.
    pub fn add_external_input(&mut self, src_port: &str, dst_node: &str, dst_port: &str) {
        self.edges.push(CompositeEdge::ExternalInput {
            src_port: src_port.to_string(),
            dst_node: dst_node.to_string(),
            dst_port: dst_port.to_string(),
        });
    }

    /// Add an external output edge.
    pub fn add_external_output(&mut self, src_node: &str, src_port: &str, dst_port: &str) {
        self.edges.push(CompositeEdge::ExternalOutput {
            src_node: src_node.to_string(),
            src_port: src_port.to_string(),
            dst_port: dst_port.to_string(),
        });
    }

    /// Add a declared block.
    pub fn add_block(&mut self, label: &str, params: &[(String, forge_ir::TypeId)]) {
        self.blocks.push(CompositeBlock {
            label: label.to_string(),
            params: params.to_vec(),
            implicit: false,
            is_merge: false,
        });
    }

    /// Add an implicit block (created by the framework).
    pub fn add_implicit_block(&mut self, label: &str) {
        self.blocks.push(CompositeBlock {
            label: label.to_string(),
            params: Vec::new(),
            implicit: true,
            is_merge: false,
        });
    }

    /// Set the implicit merge block flag.
    pub fn with_implicit_merge(mut self) -> Self {
        self.has_implicit_merge = true;
        self
    }
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::atom::arith;

    #[test]
    fn test_composite_spec_creation() {
        let mut spec = CompositeSpec::new("TestComposite");
        spec.add_input("lhs", forge_ir::TypeId::I32);
        spec.add_input("rhs", forge_ir::TypeId::I32);
        spec.add_output("result", forge_ir::TypeId::I32);
        spec.add_node(arith::iadd(), "add");
        spec.add_external_input("lhs", "add", "lhs");
        spec.add_external_input("rhs", "add", "rhs");
        spec.add_external_output("add", "result", "result");

        assert_eq!(spec.inputs.len(), 2);
        assert_eq!(spec.outputs.len(), 1);
        assert_eq!(spec.nodes.len(), 1);
        assert_eq!(spec.edges.len(), 3);
    }

    #[test]
    fn test_composite_with_implicit_merge() {
        let spec = CompositeSpec::new("IfElse").with_implicit_merge();
        assert!(spec.has_implicit_merge);
    }
}
